spring:
  application:
    name: gateway

  cloud:
    gateway:
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bda-realm/

server:
  port: 8082

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

tpi-backend:
  url-microservicio-agencia: http://localhost:8083
  url-microservicio-notificaciones: http://localhost:8084